import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import gengar from '../pages/images/gengar.png'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Poke-panel
        </h1>
        <code className={styles.code}>A simple page to show pokemon cards!</code>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <div class={styles.cardInner}>
              <div class={styles.cardFront}>
                <h2>go to the cards &rarr;</h2>
                <Image 
                  src={gengar} 
                  alt={"gengar"} 
                  width={80}
                  height={80}
                />
              </div>
              <div class={styles.cardBack}>
                <p>Find in-depth information about Next.js features and API.</p>
              </div>
            </div>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <div class={styles.cardInner}>
              <div class={styles.cardFront}>
                <h2>learn more about the API &rarr;</h2>
              </div>
              <div class={styles.cardBack}>
                <p>Learn about Next.js in an interactive course with quizzes!</p>
              </div>
            </div>
          </a>
        </div>
      </main>


      <footer className={styles.footer}>
        <a
          href="https://github.com/kairodeveloper"
          target="_blank"
          rel="noopener noreferrer"
        >
          developed by Kairo Emannoel
        </a>
      </footer>
    </div>
  )
}
