import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import logo from '../../poke-panel/images/logo_pokepanel.png'
import pokeball from '../../poke-panel/images/pokeball.png'

export default function Home() {

  function getCircles(value) {
    let retorno = []
    for (let index = 0; index < 75; index++) {
      retorno.push( <div className={styles.circleOnLight} /> )
    }

    return retorno
  }

  return (
    <div className={styles.container}>
      { getCircles(1) }
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <Image src={logo} alt={"logo"} width={300} height={100} />
        <br/>
        <code className={styles.code}>A simple page to show pokemon cards!</code>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" id={styles.leftCard} className={styles.card}>
            <div className={styles.cardInner}>
              <div className={styles.cardFront}>
                <h2>go to the cards &rarr;</h2>
                <div className={styles.pokeball} />
              </div>
              {/* <div class={styles.cardBack}>
                <p>take a look at the cards.</p>
              </div> */}
            </div>
          </a>

          <a href="https://nextjs.org/learn" id={styles.rightCard} className={styles.card}>
            <div className={styles.cardInner}>
              <div className={styles.cardFront}>
                <h2>learn more about the API &rarr;</h2>
                <div className={styles.pokeball} />
              </div>
              {/* <div class={styles.cardBack}>
                <p>learn about Pokemon TCG API</p>
              </div> */}
            </div>
          </a>
        </div>
      </main>


      <footer className={styles.footer}>
        <a
          href="https://github.com/kairodeveloper"
          target="_blank"
          rel="noopener noreferrer"
        >
          developed by Kairo Emannoel
        </a>
      </footer>
    </div>
  )
}
