import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import logo from '../../poke-panel/images/logo_pokepanel.png'
import { useState } from 'react'

export default function Home() {
  const [ShowPokeball, setShowPokeball] = useState(false)
  const [MousePosition, setMousePosition] = useState({
    left: 0,
    top: 0
  })

  function getCircles(value) {
    let retorno = []
    for (let index = 0; index < value; index++) {
      retorno.push(<div className={styles.circleOnLight} />)
    }

    return retorno
  }

  function handleMouseMove(e) {
    setMousePosition({
      left: e.pageX,
      top: e.pageY
    })
  }

  function handleOnEnter() {
    setShowPokeball(true)
  }

  function handleOnLeave() {
    setShowPokeball(false)
  }

  return (
    <div className={styles.container}
      onMouseMove={handleMouseMove}>
      {getCircles(30)}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.pokeball}
          style={{
            top: MousePosition.top + 'px',
            left: MousePosition.left + 'px',
            display: ShowPokeball ? "none" : "block"
          }}
        />
        <div className={styles.pokeballSpin}
          style={{
            top: MousePosition.top + 'px',
            left: MousePosition.left + 'px',
            display: ShowPokeball ? "block" : "none"
          }}
        />
        <Image src={logo} alt={"logo"} width={300} height={100} />
        <br />
        <code className={styles.code}>A simple page to show pokemon cards!</code>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs"
            id={styles.leftCard}
            className={styles.card}
            onMouseMove={handleOnEnter}
            onMouseEnter={handleOnEnter}
            onMouseOut={handleOnLeave}>
            <div className={styles.cardInner}>
              <div className={styles.cardFront}>
                <h2>go to the cards &rarr;</h2>
              </div>
            </div>
          </a>

          <a href="https://nextjs.org/learn" id={styles.rightCard} className={styles.card}>
            <div className={styles.cardInner}
              onMouseMove={handleOnEnter}
              onMouseEnter={handleOnEnter}
              onMouseOut={handleOnLeave}>
              <div className={styles.cardFront}>
                <h2>learn more about the API &rarr;</h2>
              </div>
            </div>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/kairodeveloper"
          target="_blank"
          rel="noopener noreferrer"
        >
          developed by Kairo Emannoel
        </a>
      </footer>
    </div >
  )
}
